/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WithName
 */
export interface WithName {
    /**
     * 
     * @type {string}
     * @memberof WithName
     */
    name: string;
}

/**
 * Check if a given object implements the WithName interface.
 */
export function instanceOfWithName(value: object): value is WithName {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WithNameFromJSON(json: any): WithName {
    return WithNameFromJSONTyped(json, false);
}

export function WithNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithName {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function WithNameToJSON(json: any): WithName {
    return WithNameToJSONTyped(json, false);
}

export function WithNameToJSONTyped(value?: WithName | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

