/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WithPassword
 */
export interface WithPassword {
    /**
     * 
     * @type {string}
     * @memberof WithPassword
     */
    password: string;
}

/**
 * Check if a given object implements the WithPassword interface.
 */
export function instanceOfWithPassword(value: object): value is WithPassword {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function WithPasswordFromJSON(json: any): WithPassword {
    return WithPasswordFromJSONTyped(json, false);
}

export function WithPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function WithPasswordToJSON(json: any): WithPassword {
    return WithPasswordToJSONTyped(json, false);
}

export function WithPasswordToJSONTyped(value?: WithPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

