// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for knex_migrations_lock */
export type Index = string;

/** Represents the table public.knex_migrations_lock */
export default interface KnexMigrationsLock {
  index: Index;

  is_locked: number | null;
}

/** Represents the initializer for the table public.knex_migrations_lock */
export interface KnexMigrationsLockInitializer {
  /** Default value: nextval('knex_migrations_lock_index_seq'::regclass) */
  index?: Index;

  is_locked?: number | null;
}

/** Represents the mutator for the table public.knex_migrations_lock */
export interface KnexMigrationsLockMutator {
  index?: Index;

  is_locked?: number | null;
}
