// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.monitor_type */
enum MonitorType {
  http = 'http',
  shell = 'shell',
};

export default MonitorType;
