// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.monitor_status */
enum MonitorStatus {
  active = "active",
  paused = "paused",
}

export default MonitorStatus;
