// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.run_status */
enum RunStatus {
  success = 'success',
  failure = 'failure',
  timeout = 'timeout',
};

export default RunStatus;
