/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { TimeSeriesChartData } from '../models';
// @ts-ignore
import type { TimeSeriesChartPayload } from '../models';
/**
 * ChartsApi - axios parameter creator
 * @export
 */
export const ChartsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Time Series Chart Data
         * @param {TimeSeriesChartPayload} timeSeriesChartPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimeSeriesChartData: async (timeSeriesChartPayload: TimeSeriesChartPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'timeSeriesChartPayload' is not null or undefined
            assertParamExists('getTimeSeriesChartData', 'timeSeriesChartPayload', timeSeriesChartPayload)
            const localVarPath = `/charts/timeSeries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(timeSeriesChartPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChartsApi - functional programming interface
 * @export
 */
export const ChartsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChartsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Time Series Chart Data
         * @param {TimeSeriesChartPayload} timeSeriesChartPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTimeSeriesChartData(timeSeriesChartPayload: TimeSeriesChartPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimeSeriesChartData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTimeSeriesChartData(timeSeriesChartPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChartsApi.getTimeSeriesChartData']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChartsApi - factory interface
 * @export
 */
export const ChartsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChartsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Time Series Chart Data
         * @param {TimeSeriesChartPayload} timeSeriesChartPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimeSeriesChartData(timeSeriesChartPayload: TimeSeriesChartPayload, options?: RawAxiosRequestConfig): AxiosPromise<TimeSeriesChartData> {
            return localVarFp.getTimeSeriesChartData(timeSeriesChartPayload, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ChartsApi - interface
 * @export
 * @interface ChartsApi
 */
export interface ChartsApiInterface {
    /**
     * 
     * @summary Get Time Series Chart Data
     * @param {TimeSeriesChartPayload} timeSeriesChartPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChartsApiInterface
     */
    getTimeSeriesChartData(timeSeriesChartPayload: TimeSeriesChartPayload, options?: RawAxiosRequestConfig): AxiosPromise<TimeSeriesChartData>;

}

/**
 * ChartsApi - object-oriented interface
 * @export
 * @class ChartsApi
 * @extends {BaseAPI}
 */
export class ChartsApi extends BaseAPI implements ChartsApiInterface {
    /**
     * 
     * @summary Get Time Series Chart Data
     * @param {TimeSeriesChartPayload} timeSeriesChartPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChartsApi
     */
    public getTimeSeriesChartData(timeSeriesChartPayload: TimeSeriesChartPayload, options?: RawAxiosRequestConfig) {
        return ChartsApiFp(this.configuration).getTimeSeriesChartData(timeSeriesChartPayload, options).then((request) => request(this.axios, this.basePath));
    }
}

