withInterfaces: true
withSeparateModelsAndApi: true
apiPackage: api
modelPackage: models
enumPropertyNaming: camelCase
apiDocs: false
modelDocs: false
apiTests: false
modelTests: false
npmName: "@pulse/apigen"
npmVersion: "0.0.0"

