/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WithId } from './with-id';
// May contain unused imports in some cases
// @ts-ignore
import type { WithMonitorType } from './with-monitor-type';
// May contain unused imports in some cases
// @ts-ignore
import type { WithName } from './with-name';

/**
 * @type Monitor
 * @export
 */
export type Monitor = WithId & WithMonitorType & WithName;


