/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MonitorConfig } from './monitor-config';
// May contain unused imports in some cases
// @ts-ignore
import type { MonitorStatus } from './monitor-status';
// May contain unused imports in some cases
// @ts-ignore
import type { MonitorType } from './monitor-type';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';
// May contain unused imports in some cases
// @ts-ignore
import type { WithAuthor } from './with-author';
// May contain unused imports in some cases
// @ts-ignore
import type { WithConfig } from './with-config';
// May contain unused imports in some cases
// @ts-ignore
import type { WithCreatedAt } from './with-created-at';
// May contain unused imports in some cases
// @ts-ignore
import type { WithId } from './with-id';
// May contain unused imports in some cases
// @ts-ignore
import type { WithMonitorType } from './with-monitor-type';
// May contain unused imports in some cases
// @ts-ignore
import type { WithName } from './with-name';
// May contain unused imports in some cases
// @ts-ignore
import type { WithSchedule } from './with-schedule';
// May contain unused imports in some cases
// @ts-ignore
import type { WithStatus } from './with-status';
// May contain unused imports in some cases
// @ts-ignore
import type { WithUpdatedAt } from './with-updated-at';

/**
 * @type Monitor
 * @export
 */
export type Monitor = WithAuthor & WithConfig & WithCreatedAt & WithId & WithMonitorType & WithName & WithSchedule & WithStatus & WithUpdatedAt;


