/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HttpConfig } from './http-config';
// May contain unused imports in some cases
// @ts-ignore
import type { HttpMethod } from './http-method';
// May contain unused imports in some cases
// @ts-ignore
import type { ShellConfig } from './shell-config';

/**
 * @type MonitorConfig
 * @export
 */
export type MonitorConfig = HttpConfig | ShellConfig;


