/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MonitorMinimal } from './monitor-minimal';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeSeriesDataPoint } from './time-series-data-point';
// May contain unused imports in some cases
// @ts-ignore
import type { WithDataPoints } from './with-data-points';
// May contain unused imports in some cases
// @ts-ignore
import type { WithMonitorMinimal } from './with-monitor-minimal';

/**
 * @type TimeSeriesMonitorData
 * @export
 */
export type TimeSeriesMonitorData = WithDataPoints & WithMonitorMinimal;


