/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChartInterval } from './chart-interval';

/**
 * 
 * @export
 * @interface TimeSeriesChartPayload
 */
export interface TimeSeriesChartPayload {
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeSeriesChartPayload
     */
    'monitorIds': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesChartPayload
     */
    'start'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesChartPayload
     */
    'end'?: string;
    /**
     * 
     * @type {ChartInterval}
     * @memberof TimeSeriesChartPayload
     */
    'interval': ChartInterval;
    /**
     * 
     * @type {ChartInterval}
     * @memberof TimeSeriesChartPayload
     */
    'timeRange': ChartInterval;
}



