/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WithMonitorType
 */
export interface WithMonitorType {
    /**
     * 
     * @type {string}
     * @memberof WithMonitorType
     */
    'monitorType': WithMonitorTypeMonitorTypeEnum;
}

export const WithMonitorTypeMonitorTypeEnum = {
    http: 'http'
} as const;

export type WithMonitorTypeMonitorTypeEnum = typeof WithMonitorTypeMonitorTypeEnum[keyof typeof WithMonitorTypeMonitorTypeEnum];


