/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WithStatus
 */
export interface WithStatus {
    /**
     * 
     * @type {string}
     * @memberof WithStatus
     */
    'status': WithStatusStatusEnum;
}

export const WithStatusStatusEnum = {
    active: 'active',
    paused: 'paused'
} as const;

export type WithStatusStatusEnum = typeof WithStatusStatusEnum[keyof typeof WithStatusStatusEnum];


