openapi: 3.1.0
info:
  title: api
  description: ""
  version: 0.0.0
paths:
  /repos:
    get:
      tags:
        - repo
      summary: List Repos
      operationId: listRepos
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Repo"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - repo
      summary: Create Repo
      operationId: createRepo
      requestBody:
        $ref: "#/components/requestBodies/CreateRepoPayload"
      responses:
        "201":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Repo"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    Repo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
    ErrorResponse:
      required:
        - message
      type: object
      properties:
        message:
          type: string
  requestBodies:
    CreateRepoPayload:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                example: my-repo
  responses:
    InternalServerError:
      description: "500"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
