openapi: 3.0.0
info:
  title: Pulse API
  description: ""
  version: 0.0.0
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: User Login
      operationId: login
      requestBody:
        $ref: "#/components/requestBodies/LoginBody"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /monitors:
    get:
      tags:
        - monitor
      summary: List Monitors
      operationId: listMonitors
      security:
        - bearerAuth: []
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Monitor"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - monitor
      summary: Create Monitor
      operationId: createMonitor
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/CreateMonitorBody"
      responses:
        "201":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Monitor"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    WithId:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
    WithName:
      required:
        - name
      type: object
      properties:
        name:
          type: string
    Monitor:
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithName"
    CreateMonitorPayload:
      allOf:
        - $ref: "#/components/schemas/WithName"
    WithUsername:
      required:
        - username
      type: object
      properties:
        username:
          type: string
    WithPassword:
      required:
        - password
      type: object
      properties:
        password:
          type: string
    LoginPayload:
      allOf:
        - $ref: "#/components/schemas/WithUsername"
        - $ref: "#/components/schemas/WithPassword"
    WithToken:
      required:
        - token
      type: object
      properties:
        token:
          type: string
    LoginResponse:
      allOf:
        - $ref: "#/components/schemas/WithToken"
        - $ref: "#/components/schemas/WithUser"
    User:
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithUsername"
    WithUser:
      required:
        - user
      type: object
      properties:
        user:
          $ref: "#/components/schemas/User"
    ErrorResponse:
      required:
        - message
      type: object
      properties:
        message:
          type: string
  requestBodies:
    LoginBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/LoginPayload"
    CreateMonitorBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateMonitorPayload"
  responses:
    UnauthorizedError:
      description: "401"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    InternalServerError:
      description: "500"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
