openapi: 3.1.0
info:
  title: api
  description: ""
  version: 0.0.0
paths:
  /repos:
    get:
      tags:
        - repo
      summary: List Repos
      operationId: listRepos
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Repo"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    Repo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
    ErrorResponse:
      required:
        - message
      type: object
      properties:
        message:
          type: string
  requestBodies: {}
  responses:
    InternalServerError:
      description: "500"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
