openapi: 3.0.0
info:
  title: Pulse API
  description: ""
  version: 0.0.0
paths:
  /monitors:
    get:
      tags:
        - monitor
      summary: List Monitors
      operationId: listMonitors
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Monitor"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - monitor
      summary: Create Monitor
      operationId: createMonitor
      requestBody:
        $ref: "#/components/requestBodies/CreateMonitorBody"
      responses:
        "201":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Monitor"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    WithId:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
    WithName:
      required:
        - name
      type: object
      properties:
        name:
          type: string
    Monitor:
      allOf:
        - $ref: "#/components/schemas/WithId"
        - $ref: "#/components/schemas/WithName"
    CreateMonitorPayload:
      allOf:
        - $ref: "#/components/schemas/WithName"
    ErrorResponse:
      required:
        - message
      type: object
      properties:
        message:
          type: string
  requestBodies:
    CreateMonitorBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateMonitorPayload'
  responses:
    InternalServerError:
      description: "500"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
