// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { default as MonitorType } from './MonitorType';

/** Identifier type for public.monitors */
export type MonitorsId = string & { __brand: 'public.monitors' };

/** Represents the table public.monitors */
export default interface Monitors {
  id: MonitorsId;

  author: UsersId;

  monitor_type: MonitorType;

  name: string;

  description: string | null;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.monitors */
export interface MonitorsInitializer {
  id: MonitorsId;

  author: UsersId;

  monitor_type: MonitorType;

  name: string;

  description?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.monitors */
export interface MonitorsMutator {
  id?: MonitorsId;

  author?: UsersId;

  monitor_type?: MonitorType;

  name?: string;

  description?: string | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}
