/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateRepoRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { Repo } from '../models';
/**
 * RepoApi - axios parameter creator
 * @export
 */
export const RepoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Repo
         * @param {CreateRepoRequest} createRepoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRepo: async (createRepoRequest: CreateRepoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createRepoRequest' is not null or undefined
            assertParamExists('createRepo', 'createRepoRequest', createRepoRequest)
            const localVarPath = `/repos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRepoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Repos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRepos: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/repos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RepoApi - functional programming interface
 * @export
 */
export const RepoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RepoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Repo
         * @param {CreateRepoRequest} createRepoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRepo(createRepoRequest: CreateRepoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Repo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRepo(createRepoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RepoApi.createRepo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Repos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRepos(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Repo>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRepos(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RepoApi.listRepos']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RepoApi - factory interface
 * @export
 */
export const RepoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RepoApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Repo
         * @param {CreateRepoRequest} createRepoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRepo(createRepoRequest: CreateRepoRequest, options?: RawAxiosRequestConfig): AxiosPromise<Repo> {
            return localVarFp.createRepo(createRepoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Repos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRepos(options?: RawAxiosRequestConfig): AxiosPromise<Array<Repo>> {
            return localVarFp.listRepos(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RepoApi - interface
 * @export
 * @interface RepoApi
 */
export interface RepoApiInterface {
    /**
     * 
     * @summary Create Repo
     * @param {CreateRepoRequest} createRepoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepoApiInterface
     */
    createRepo(createRepoRequest: CreateRepoRequest, options?: RawAxiosRequestConfig): AxiosPromise<Repo>;

    /**
     * 
     * @summary List Repos
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepoApiInterface
     */
    listRepos(options?: RawAxiosRequestConfig): AxiosPromise<Array<Repo>>;

}

/**
 * RepoApi - object-oriented interface
 * @export
 * @class RepoApi
 * @extends {BaseAPI}
 */
export class RepoApi extends BaseAPI implements RepoApiInterface {
    /**
     * 
     * @summary Create Repo
     * @param {CreateRepoRequest} createRepoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepoApi
     */
    public createRepo(createRepoRequest: CreateRepoRequest, options?: RawAxiosRequestConfig) {
        return RepoApiFp(this.configuration).createRepo(createRepoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Repos
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepoApi
     */
    public listRepos(options?: RawAxiosRequestConfig) {
        return RepoApiFp(this.configuration).listRepos(options).then((request) => request(this.axios, this.basePath));
    }
}

