/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMonitorPayload
 */
export interface CreateMonitorPayload {
    /**
     * 
     * @type {string}
     * @memberof CreateMonitorPayload
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMonitorPayload
     */
    monitorType: CreateMonitorPayloadMonitorTypeEnum;
}


/**
 * @export
 */
export const CreateMonitorPayloadMonitorTypeEnum = {
    Http: 'http'
} as const;
export type CreateMonitorPayloadMonitorTypeEnum = typeof CreateMonitorPayloadMonitorTypeEnum[keyof typeof CreateMonitorPayloadMonitorTypeEnum];


/**
 * Check if a given object implements the CreateMonitorPayload interface.
 */
export function instanceOfCreateMonitorPayload(value: object): value is CreateMonitorPayload {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('monitorType' in value) || value['monitorType'] === undefined) return false;
    return true;
}

export function CreateMonitorPayloadFromJSON(json: any): CreateMonitorPayload {
    return CreateMonitorPayloadFromJSONTyped(json, false);
}

export function CreateMonitorPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonitorPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'monitorType': json['monitorType'],
    };
}

export function CreateMonitorPayloadToJSON(json: any): CreateMonitorPayload {
    return CreateMonitorPayloadToJSONTyped(json, false);
}

export function CreateMonitorPayloadToJSONTyped(value?: CreateMonitorPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'monitorType': value['monitorType'],
    };
}

