/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginPayload
 */
export interface LoginPayload {
    /**
     * 
     * @type {string}
     * @memberof LoginPayload
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LoginPayload
     */
    password: string;
}

/**
 * Check if a given object implements the LoginPayload interface.
 */
export function instanceOfLoginPayload(value: object): value is LoginPayload {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginPayloadFromJSON(json: any): LoginPayload {
    return LoginPayloadFromJSONTyped(json, false);
}

export function LoginPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LoginPayloadToJSON(json: any): LoginPayload {
    return LoginPayloadToJSONTyped(json, false);
}

export function LoginPayloadToJSONTyped(value?: LoginPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

