/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Monitor
 */
export interface Monitor {
    /**
     * 
     * @type {string}
     * @memberof Monitor
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Monitor
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Monitor
     */
    monitorType: MonitorMonitorTypeEnum;
}


/**
 * @export
 */
export const MonitorMonitorTypeEnum = {
    Http: 'http'
} as const;
export type MonitorMonitorTypeEnum = typeof MonitorMonitorTypeEnum[keyof typeof MonitorMonitorTypeEnum];


/**
 * Check if a given object implements the Monitor interface.
 */
export function instanceOfMonitor(value: object): value is Monitor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('monitorType' in value) || value['monitorType'] === undefined) return false;
    return true;
}

export function MonitorFromJSON(json: any): Monitor {
    return MonitorFromJSONTyped(json, false);
}

export function MonitorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Monitor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'monitorType': json['monitorType'],
    };
}

export function MonitorToJSON(json: any): Monitor {
    return MonitorToJSONTyped(json, false);
}

export function MonitorToJSONTyped(value?: Monitor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'monitorType': value['monitorType'],
    };
}

