/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WithUsername
 */
export interface WithUsername {
    /**
     * 
     * @type {string}
     * @memberof WithUsername
     */
    username: string;
}

/**
 * Check if a given object implements the WithUsername interface.
 */
export function instanceOfWithUsername(value: object): value is WithUsername {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function WithUsernameFromJSON(json: any): WithUsername {
    return WithUsernameFromJSONTyped(json, false);
}

export function WithUsernameFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithUsername {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function WithUsernameToJSON(json: any): WithUsername {
    return WithUsernameToJSONTyped(json, false);
}

export function WithUsernameToJSONTyped(value?: WithUsername | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

