/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WithToken
 */
export interface WithToken {
    /**
     * 
     * @type {string}
     * @memberof WithToken
     */
    token: string;
}

/**
 * Check if a given object implements the WithToken interface.
 */
export function instanceOfWithToken(value: object): value is WithToken {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function WithTokenFromJSON(json: any): WithToken {
    return WithTokenFromJSONTyped(json, false);
}

export function WithTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithToken {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function WithTokenToJSON(json: any): WithToken {
    return WithTokenToJSONTyped(json, false);
}

export function WithTokenToJSONTyped(value?: WithToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

