/* tslint:disable */
/* eslint-disable */
/**
 * Pulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface WithUser
 */
export interface WithUser {
    /**
     * 
     * @type {User}
     * @memberof WithUser
     */
    user: User;
}

/**
 * Check if a given object implements the WithUser interface.
 */
export function instanceOfWithUser(value: object): value is WithUser {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function WithUserFromJSON(json: any): WithUser {
    return WithUserFromJSONTyped(json, false);
}

export function WithUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithUser {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
    };
}

export function WithUserToJSON(json: any): WithUser {
    return WithUserToJSONTyped(json, false);
}

export function WithUserToJSONTyped(value?: WithUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserToJSON(value['user']),
    };
}

