// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.repos */
export type ReposId = string & { __brand: 'public.repos' };

/** Represents the table public.repos */
export default interface Repos {
  id: ReposId;

  name: string;

  description: string | null;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.repos */
export interface ReposInitializer {
  id: ReposId;

  name: string;

  description?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.repos */
export interface ReposMutator {
  id?: ReposId;

  name?: string;

  description?: string | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}
